### PR TITLE
Fix musl build

### LINKED ISSUE #8: Doesn't compile on Mac with target for Docker
```
cargo build --bin client --target x86_64-unknown-linux-musl
```
results in
```
error: cannot construct `msghdr` with struct literal syntax due to inaccessible fields
  --> /Users/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/passfd-0.1.4/src/lib.rs:89:27
   |
89 |         let msg: msghdr = libc::msghdr {
   |                           ^^^^^^^^^^^^

error[E0063]: missing field `__pad1` in initializer of `cmsghdr`
   --> /Users/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/passfd-0.1.4/src/lib.rs:100:23
    |
100 |             let hdr = libc::cmsghdr {
    |                       ^^^^^^^^^^^^^ missing `__pad1`

error: cannot construct `msghdr` with struct literal syntax due to inaccessible fields
   --> /Users/alan/.cargo/registry/src/github.com-1ecc6299db9ec823/passfd-0.1.4/src/lib.rs:133:31
    |
133 |         let mut msg: msghdr = libc::msghdr {
    |                               ^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by polachok**
Fixes https://github.com/polachok/passfd/issues/8

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -86,22 +87,28 @@ impl FdPassingExt for RawFd {
...
-        let msg: msghdr = libc::msghdr {
-            msg_name: std::ptr::null_mut(),
-            msg_namelen: 0,
-            msg_iov: &mut iov,
-            msg_iovlen: 1,
-            msg_control: unsafe { u.buf.as_mut_ptr() as *mut c_void },
-            msg_controllen: msg_len,
-            msg_flags: 0,
-        };
+        let mut msg: MaybeUninit<msghdr> = MaybeUninit::uninit();
```
Comment (lhchavez) [inline src/lib.rs]:
```suggestion
        let mut msg: MaybeUninit<msghdr> = MaybeUninit::zeroed();
```

i think this may be a bit safer and more portable.

**Review by lhchavez — APPROVED** [review]
any chance this can get merged any time soon? i depend on this crate in several projects and this change enables compiling static binaries with musl!
